// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'profile_details_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProfileDetailsModel _$ProfileDetailsModelFromJson(Map<String, dynamic> json) =>
    ProfileDetailsModel(
      success: json['success'],
      data: UserData.fromJson(json['data'] as Map<String, dynamic>),
      extraData: json['extra_data'],
      message: json['message'],
      meta: json['meta'],
    );

Map<String, dynamic> _$ProfileDetailsModelToJson(
  ProfileDetailsModel instance,
) => <String, dynamic>{
  'success': instance.success,
  'data': instance.data,
  'extra_data': instance.extraData,
  'message': instance.message,
  'meta': instance.meta,
};

UserData _$UserDataFromJson(Map<String, dynamic> json) => UserData(
  id: json['id'],
  name: json['name'],
  username: json['username'],
  email: json['email'],
  emailVerifiedAt: json['email_verified_at'],
  countryCode: json['country_code'],
  mobile: json['mobile'],
  mobileVerifiedAt: json['mobile_verified_at'],
  role: json['role'],
  department: json['department'],
  designation: json['designaton'],
  otp: json['otp'],
  otpVerified: json['otp_verified'],
  thawaniId: json['thawani_id'],
  googleId: json['google_id'],
  fbId: json['fb_id'],
  avatar: json['avatar'],
  signature: json['signature'],
  isCompany: json['is_company'],
  isClient: json['is_client'],
  authorityName: json['authority_name'],
  fileAuthLetter: json['file_auth_letter'],
  residentCardNumber: json['resident_card_number'],
  fileIdNumber: json['file_id_number'],
  bank: json['bank'],
  accountNumber: json['account_number'],
  beneficiary: json['beneficiary'],
  crNumber: json['cr_number'],
  crExpiryDate: json['cr_expiry_date'],
  fileCrNumber: json['file_cr_number'],
  vatNumber: json['vat_number'],
  fileVatCertificate: json['file_vat_certificate'],
  fileAdditionalDoc: json['file_additional_doc'],
  walletAmount: json['wallet_amount'],
  holdAmount: json['hold_amount'],
  isRopStaff: json['is_rop_staff'],
  departmentId: json['department_id'],
  lastSeenAt: json['last_seen_at'],
  status: json['status'],
  deleted: json['deleted'],
  deletedAt: json['deleted_at'],
  createdAt: json['created_at'],
  updatedAt: json['updated_at'],
  bidderNumber: json['bidder_number'],
);

Map<String, dynamic> _$UserDataToJson(UserData instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'username': instance.username,
  'email': instance.email,
  'email_verified_at': instance.emailVerifiedAt,
  'country_code': instance.countryCode,
  'mobile': instance.mobile,
  'mobile_verified_at': instance.mobileVerifiedAt,
  'role': instance.role,
  'department': instance.department,
  'designaton': instance.designation,
  'otp': instance.otp,
  'otp_verified': instance.otpVerified,
  'thawani_id': instance.thawaniId,
  'google_id': instance.googleId,
  'fb_id': instance.fbId,
  'avatar': instance.avatar,
  'signature': instance.signature,
  'is_company': instance.isCompany,
  'is_client': instance.isClient,
  'authority_name': instance.authorityName,
  'file_auth_letter': instance.fileAuthLetter,
  'resident_card_number': instance.residentCardNumber,
  'file_id_number': instance.fileIdNumber,
  'bank': instance.bank,
  'account_number': instance.accountNumber,
  'beneficiary': instance.beneficiary,
  'cr_number': instance.crNumber,
  'cr_expiry_date': instance.crExpiryDate,
  'file_cr_number': instance.fileCrNumber,
  'vat_number': instance.vatNumber,
  'file_vat_certificate': instance.fileVatCertificate,
  'file_additional_doc': instance.fileAdditionalDoc,
  'wallet_amount': instance.walletAmount,
  'hold_amount': instance.holdAmount,
  'is_rop_staff': instance.isRopStaff,
  'department_id': instance.departmentId,
  'last_seen_at': instance.lastSeenAt,
  'status': instance.status,
  'deleted': instance.deleted,
  'deleted_at': instance.deletedAt,
  'created_at': instance.createdAt,
  'updated_at': instance.updatedAt,
  'bidder_number': instance.bidderNumber,
};
